#!/bin/bash
nbits=(32 48)
niter=(0 1)
folders=("y10_u2" "y20_u4" "y50_u10")
# for folder in ${folders[@]}; do
# 	rm -r Data
# 	cp -r all_data/${folder} ./Data
# 	tree ./Data
# 	for j in ${niter[@]}; do
# 		for i in ${nbits[@]}; do
# 			(valgrind --tool=callgrind build/bin/system 1 12345 $j $i) & (sleep 0.1; valgrind --tool=callgrind build/bin/cloud 2 12345 $j $i)
# 			mv callgrind* ./results/gates/${i}_bit/system_generator/${folder}/
# 			sleep 1
# 		done
# 	done
# 	for j in ${niter[@]}; do
# 		for i in ${nbits[@]}; do
# 			(valgrind --tool=callgrind build/bin/system 2 12345 $j $i) & (sleep 0.1; valgrind --tool=callgrind build/bin/cloud 1 12345 $j $i)
# 			mv callgrind* ./results/gates/${i}_bit/system_evaluator/${folder}/
# 			sleep 1
# 		done
# 	done
# done
for folder in ${folders[@]}; do
	rm -r Data
	cp -r all_data/${folder} ./Data
	tree ./Data
	for j in ${niter[@]}; do
		for i in ${nbits[@]}; do
			(valgrind --tool=callgrind build/bin/system_hybrid 1 12345 $j $i) & (sleep 0.1; valgrind --tool=callgrind build/bin/cloud_hybrid 2 12345 $j $i)
			sleep 1
			mv callgrind* ./results/gates/${i}_bit/hybrid/${folder}/
			sleep 1
		done
	done
done
